/*
 * Copyright 2024 SiriusXM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package snapshot4s

import java.io.File
import java.util.regex.Pattern

/** Core snapshot4s plugin logic. This is shared between SBT and mill plugins. */
private object Plugin {

  def scalacOptions(scalaVersion: String): Seq[String] = {
    if (scalaVersion.startsWith("3.")) {
      Nil
    } else {
      Seq(
        "-Yrangepos" // makes the compiler collect position metadata
      )
    }
  }

  def defaultResourceDirectory(resources: File) = new File(resources, "snapshot")

  def sourceGenerator(
      fileIO: FileIO
  )(resourceDir: File, patchDir: File, sourceDirs: Seq[File], destDir: File): File = {
    val sourceDir   = sourceBaseDirectory(sourceDirs)
    val tripleQuote = "\"\"\""
    val text        = s"""package snapshot4s

/** This object was generated by snapshot4s. */
object generated {
  implicit val snapshotConfig: SnapshotConfig = new SnapshotConfig(
    resourceDirectory = Path($tripleQuote${resourceDir}$tripleQuote),
    outputDirectory = Path($tripleQuote${patchDir}$tripleQuote),
    sourceDirectory = Path($tripleQuote${sourceDir}$tripleQuote)
  )
}
 """
    val dest = new File(destDir, "Snapshot4sBuildInfo.scala")
    fileIO.write(dest, text)
    dest
  }

  private def makeFilter(arguments: Seq[String]): String => Boolean = {
    val globPatterns = arguments.map(_.trim).filter(_.nonEmpty)
    if (globPatterns.isEmpty) Function.const(true)
    else
      globPatterns
        .map(globFilter)
        .reduce((fa, fb) => (name: String) => fa(name) || fb(name))
  }

  private def globFilter(expression: String): String => Boolean = {
    val regex = expression
      .split("\\*", -1)
      .map(Pattern.quote)
      .mkString(".*")
    val pattern = Pattern.compile(regex)
    (name: String) => pattern.matcher(name).matches
  }

  private def sourceBaseDirectory(sourceDirectories: Seq[File]): File = {
    def sharedParent(dirA: File, dirB: File): File = {
      if (dirB.getAbsolutePath().startsWith(dirA.getAbsolutePath())) dirA
      else if (dirA.getAbsolutePath().startsWith(dirB.getAbsolutePath())) dirB
      else sharedParent(dirA.getParentFile, dirB)
    }
    sourceDirectories.reduce(sharedParent)
  }

  def applyResourcePatches(
      logInfo: String => Unit,
      fileIO: FileIO
  )(patchDir: File, resourceDir: File, arguments: Seq[String]): Unit = {
    val resourcePatchDir = new File(patchDir, "resource-patch")
    val filter           = makeFilter(arguments)
    val patches          = fileIO.listMatchingFiles(resourcePatchDir, !_.isDirectory)
    val filteredPatches  = patches.filter(file => filter(file.getParent))
    filteredPatches.foreach { patchFile =>
      val patchContents = fileIO.read(patchFile)
      val sourceFile    = locateResourceFile(fileIO)(resourcePatchDir, patchFile, resourceDir)
      fileIO.delete(patchFile)
      fileIO.write(sourceFile, patchContents)
      logInfo(s"Patch applied to $sourceFile")
    }
  }

  private def locateResourceFile(
      fileIO: FileIO
  )(resourcePatchDir: File, patchFile: File, resourceDir: File) = {
    val relativePath =
      fileIO.relativize(resourcePatchDir, patchFile)
    // relative path starts with subpath like "src/test/scala/MyTest.scala" we need to remove that
    val withoutSourceTestFileName = relativePath.split("\\.scala").tail
    withoutSourceTestFileName.foldRight(resourceDir) { (component, path) =>
      new File(path, component)
    }
  }

  def applyInlinePatches(
      logInfo: String => Unit,
      logWarn: String => Unit,
      fileIO: FileIO
  )(patchDir: File, sourceDirs: Seq[File], arguments: Seq[String]) = {
    val sourceDir        = sourceBaseDirectory(sourceDirs)
    val inlinePatchDir   = new File(patchDir, "inline-patch")
    val filter           = makeFilter(arguments)
    val patchDirectories = fileIO.listMatchingFiles(inlinePatchDir, !_.isDirectory)
    val dirsByParent     = patchDirectories.groupBy(_.getParent).filter { case (k, _) =>
      filter(k)
    }
    dirsByParent.foreach { case (parentDir, changeFiles) =>
      val relativeSourceFile = fileIO.relativize(inlinePatchDir, new File(parentDir))
      val sourceFile         = new File(sourceDir, relativeSourceFile)
      val sourceContents     = fileIO.read(sourceFile)

      val sourceFileHash = Hashing.calculateHash(sourceContents)

      val changes = changeFiles.toList.mapFilter { changeFile =>
        val (start, end) = parseChangeFileName(changeFile.getName)
        val contents     = fileIO.read(changeFile)

        Hashing.verifyAndRemoveHash(sourceFileHash)(contents) match {
          case None =>
            logWarn(
              s"Can't apply patch to $relativeSourceFile, most likely it was modified after executing tests. " +
                s"Please re-run the test and try again."
            )
            None
          case Some(patchContent) => Some((start, end, patchContent))
        }
      }.toList

      changes match {
        case Nil          => ()
        case nonEmptyList =>
          val patchedSource = applyPatch(sourceContents, nonEmptyList)
          fileIO.write(sourceFile, patchedSource)
          logInfo(s"Patch applied to $sourceFile")
          changeFiles.foreach(fileIO.delete)
      }
    }

  }

  private def parseChangeFileName(str: String): (Int, Int) = {
    str.split("-").toList match {
      case startPos :: endPos :: Nil => (startPos.toInt, endPos.toInt)
      case _                         =>
        sys.error(
          s"Unable to parse change file name ${str}. There is a bug in the snapshot4s plugin."
        )
    }
  }

  private def applyPatch(source: String, patches: List[(Int, Int, String)]): String = {
    patches
      .sortBy(_._1)
      .foldLeft((source, 0))((acc, patch) => {
        val (source, offset)           = acc
        val (startPos, endPos, middle) = patch
        val start                      = source.take(offset + startPos)
        val end                        = source.drop(offset + endPos)
        val nextSource                 = start ++ middle ++ end
        val lengthIncrease             = middle.length - (endPos - startPos)
        val nextOffset                 = offset + lengthIncrease
        (nextSource, nextOffset)
      })
      ._1
  }

  private implicit class MapFilter[A](list: List[A]) {
    def mapFilter[B](f: A => Option[B]): List[B] =
      list.map(f).filter(_.isDefined).map(_.get)
  }

}
